import Head from "next/head";
import Image from "next/image";
//import styles from "@/styles/Home.module.css";

export default function Home() {
  const scrapeData = async () => {
    fetch(
      "http://localhost:3000/api/crawl?urls=https://syndic8.io&limit=10&indexName=syndic8",
      {
        method: "GET",
        mode: "no-cors",
        headers: {
          "Content-Type": "application/json",
        },
      }
    )
      .then((res) => res.json())
      .then((data) => console.log(data))
      .catch((err) => console.log(err));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => scrapeData()}>Scrape</button>
      </main>
    </>
  );
}
